In [3]:
import pandas as pd
data = pd.read_csv("student_scores.csv")
data.head(10)

     name  hours  score gender grades class
0   Aarav      8    NaN      M      A    9A
1    Riya      5   62.0      F      B    9B
2   Kabir     10   88.0      M      A   10A
3    Sana      4   55.0      F      C    9A
4  Vivaan      7   72.0      M      B   10B
5  Ishita      6   64.0      F      B    9C
6   Rohan      3   48.0      M      D    9B
7   Meera      9   90.0      F      A   11A
8  Aditya      2   38.0      M      F    9C
9   Kavya     11   93.0      F      A   12A

In [4]:
print('Columns:', data.columns.tolist())
print('\nInfo:')
print(data.info())
print('\nDescribe:')
display(data.describe())
print("Shape:",data.shape)

Columns: ['name', 'hours', 'score', 'gender', 'grades', 'class']

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    92 non-null     object
 1   hours   92 non-null     int64
 2   score   91 non-null     float64
 3   gender  92 non-null     object
 4   grades  92 non-null     object
 5   class   92 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.4+ KB
None

Describe:

           hours      score
count  92.000000  91.000000
mean    6.510870  68.758242
std     2.265336  15.760951
min     2.000000  35.000000
25%     5.000000  57.000000
50%     7.000000  70.000000
75%     8.000000  82.000000
max    11.000000  94.000000

Shape: (92, 6)

# Handling Missing Value

In [5]:
#check for missing values:
print(data.isnull().sum())

#Option 1: Fill missing values with mean
data["score"] = data["score"].fillna(data["score"].mean())

#Option 2: Drop rows with missing values
#data = data.dropna()

name      0
hours     0
score     1
gender    0
grades    0
class     0
dtype: int64

In [6]:
print(data)

       name  hours      score gender grades class
0     Aarav      8  68.758242      M      A    9A
1      Riya      5  62.000000      F      B    9B
2     Kabir     10  88.000000      M      A   10A
3      Sana      4  55.000000      F      C    9A
4    Vivaan      7  72.000000      M      B   10B
..      ...    ...        ...    ...    ...   ...
87   Prisha      4  52.000000      F      C    9A
88     Neil     10  88.000000      M      A   12C
89    Rutvi      7  73.000000      F      B   10A
90  Harshit      5  57.000000      M      C    9B
91   Vritti      8  81.000000      F      A   11B

[92 rows x 6 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#option 1:
#data["gender"] = le.fit_transform(data["gender"])
#option 2:
data["gender"]=data["gender"].map({'M':1,'F':0})
print(data.head(20))

       name  hours      score  gender grades class
0     Aarav      8  68.758242       1      A    9A
1      Riya      5  62.000000       0      B    9B
2     Kabir     10  88.000000       1      A   10A
3      Sana      4  55.000000       0      C    9A
4    Vivaan      7  72.000000       1      B   10B
5    Ishita      6  64.000000       0      B    9C
6     Rohan      3  48.000000       1      D    9B
7     Meera      9  90.000000       0      A   11A
8    Aditya      2  38.000000       1      F    9C
9     Kavya     11  93.000000       0      A   12A
10    Naman      5  60.000000       1      B   10A
11   Jhanvi      7  70.000000       0      B   11B
12   Pranav      4  52.000000       1      C    9A
13     Tara      9  85.000000       0      A   12B
14     Yash      6  66.000000       1      B   10C
15    Anaya      8  78.000000       0      A   11A
16    Harsh      3  45.000000       1      D    9A
17     Diya     10  89.000000       0      A   12C
18  Sarthak      6  63.000000       1      B   10B
19    Manya      7  74.000000       0      B   11B

In [8]:
le = LabelEncoder()
data["class_encoded"] = le.fit_transform(data["grades"])

In [9]:
x = data[["hours","class_encoded"]]
y = data["score"]

In [10]:
print(data)

       name  hours      score  gender grades class  class_encoded
0     Aarav      8  68.758242       1      A    9A              0
1      Riya      5  62.000000       0      B    9B              1
2     Kabir     10  88.000000       1      A   10A              0
3      Sana      4  55.000000       0      C    9A              2
4    Vivaan      7  72.000000       1      B   10B              1
..      ...    ...        ...     ...    ...   ...            ...
87   Prisha      4  52.000000       0      C    9A              2
88     Neil     10  88.000000       1      A   12C              0
89    Rutvi      7  73.000000       0      B   10A              1
90  Harshit      5  57.000000       1      C    9B              2
91   Vritti      8  81.000000       0      A   11B              0

[92 rows x 7 columns]

In [11]:
print(x,y)

    hours  class_encoded
0       8              0
1       5              1
2      10              0
3       4              2
4       7              1
..    ...            ...
87      4              2
88     10              0
89      7              1
90      5              2
91      8              0

[92 rows x 2 columns] 0     68.758242
1     62.000000
2     88.000000
3     55.000000
4     72.000000
        ...
87    52.000000
88    88.000000
89    73.000000
90    57.000000
91    81.000000
Name: score, Length: 92, dtype: float64

In [12]:
#Normalization
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

#Load dataset
data = pd.read_csv("student_scores.csv")

#Encode class column
le = LabelEncoder()
data["class_encoded"] = le.fit_transform(data["grades"])

#Select features (exclude name, gender)
X = data[["hours","class_encoded"]]
Y = data["score"]

#Train/test split
X_train, X_test, Y_train, Y_test = train_test_split(
    X,Y, test_size=0.2, random_state=42
)

#Scale
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [14]:
X, Y,

(    hours  class_encoded
 0       8              0
 1       5              1
 2      10              0
 3       4              2
 4       7              1
 ..    ...            ...
 87      4              2
 88     10              0
 89      7              1
 90      5              2
 91      8              0

 [92 rows x 2 columns],
 0      NaN
 1     62.0
 2     88.0
 3     55.0
 4     72.0
       ...
 87    52.0
 88    88.0
 89    73.0
 90    57.0
 91    81.0
 Name: score, Length: 92, dtype: float64)

In [20]:
 X_train, Y_train ,X_test, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
X_train

    hours  class_encoded
65      8              0
15      8              0
68      7              1
78      6              1
30      5              2
..    ...            ...
20      8              0
60      4              2
71      6              1
14      6              1
51     10              0

[73 rows x 2 columns]

In [18]:
 X_train, Y_train ,X_test, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)
print('Y_train shape:', Y_train.shape)
print('Y_test shape:', Y_test.shape)
print("Mean:", X_train_scaled.mean(axis=0))
print("Std:", X_train_scaled.std(axis=0))

X_train shape: (73, 2)
X_test shape: (73,)
Y_train shape: (19, 2)
Y_test shape: (19,)
Mean: [-7.90843798e-17  5.77924314e-17]
Std: [1. 1.]